version: "3.8"
services:
  db:
    image: juliendosiere/localhub-db
  backend:
    image: juliendosiere/localhub-backend
    ports:
    - 3000:3000
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://localhub:localhub@db/localhub
  frontend:
    image: juliendosiere/localhub-frontend
    ports:
      - 8080:8080
    depends_on:
      - backend
